# Generated by Django 5.2.7 on 2025-11-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=100)),
                ('u_email', models.EmailField(max_length=254)),
                ('u_subject', models.CharField(max_length=100)),
                ('u_message', models.CharField(max_length=100)),
            ],
        ),
    ]
