# Generated by Django 5.2.7 on 2025-11-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameraapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_map_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapp', models.CharField(max_length=500)),
            ],
        ),
    ]
