# Generated by Django 5.2.7 on 2025-11-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameraapp', '0002_contact_map_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='quote_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_name', models.CharField(max_length=100)),
                ('q_email', models.EmailField(max_length=254)),
                ('q_mo_no', models.BigIntegerField()),
                ('q_select_ser', models.CharField(max_length=100)),
                ('q_note', models.CharField(max_length=100)),
            ],
        ),
    ]
