# Generated by Django 5.2.7 on 2025-11-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameraapp', '0003_quote_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='quote_img_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default=None, max_length=300, null=True, upload_to='static')),
                ('q_title', models.CharField(max_length=100)),
                ('q_info', models.CharField(max_length=100)),
            ],
        ),
    ]
