# Generated by Django 5.2.7 on 2025-11-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameraapp', '0004_quote_img_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='team_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('img', models.ImageField(default=None, max_length=300, null=True, upload_to='static')),
                ('f_link', models.CharField(max_length=100)),
                ('t_link', models.CharField(max_length=100)),
                ('i_link', models.CharField(max_length=100)),
            ],
        ),
    ]
