# Generated by Django 5.2.7 on 2025-11-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameraapp', '0005_team_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='project_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default=None, max_length=300, null=True, upload_to='static')),
                ('p_title', models.CharField(max_length=100)),
                ('p_info', models.CharField(max_length=100)),
                ('y_link', models.CharField(max_length=100)),
                ('t_link', models.CharField(max_length=100)),
            ],
        ),
    ]
