# Generated by Django 5.2.7 on 2025-11-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameraapp', '0007_service_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='about_sub_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default=None, max_length=300, null=True, upload_to='static')),
                ('a_no', models.IntegerField()),
                ('a_info', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='about_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default=None, max_length=300, null=True, upload_to='static')),
                ('a_title', models.CharField(max_length=100)),
                ('a_info', models.CharField(max_length=100)),
            ],
        ),
    ]
