# Generated by Django 5.2.7 on 2025-11-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameraapp', '0009_about_card_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default=None, null=True, upload_to='static/img')),
                ('message', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('profession', models.CharField(max_length=200)),
            ],
        ),
    ]
