# Generated by Django 5.2.7 on 2025-11-25 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameraapp', '0010_testimonial_tbl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial_tbl',
        ),
    ]
