# Generated by Django 5.2.7 on 2025-11-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameraapp', '0011_delete_testimonial_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='feature_sub_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default=None, max_length=300, null=True, upload_to='static')),
                ('f_title', models.CharField(max_length=100)),
                ('f_info', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='feature_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default=None, max_length=300, null=True, upload_to='static')),
                ('f_title', models.CharField(max_length=100)),
                ('f_info', models.CharField(max_length=100)),
            ],
        ),
    ]
