# Generated by Django 5.2.7 on 2025-11-25 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameraapp', '0012_feature_sub_tbl_feature_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='testi_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default=None, max_length=300, null=True, upload_to='static')),
                ('t_info', models.CharField(max_length=200)),
                ('t_name', models.CharField(max_length=100)),
                ('t_possion', models.CharField(max_length=100)),
            ],
        ),
    ]
