# Generated by Django 5.2.7 on 2025-11-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameraapp', '0013_testi_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='index_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_img', models.ImageField(default=None, max_length=300, null=True, upload_to='static')),
                ('h_title', models.CharField(max_length=200)),
                ('h_p', models.CharField(max_length=400)),
            ],
        ),
    ]
