# Generated by Django 5.2.7 on 2025-11-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameraapp', '0014_index_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='topbar_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=300)),
                ('top_email', models.EmailField(max_length=254)),
                ('top_mo', models.BigIntegerField()),
                ('date', models.CharField(max_length=200)),
            ],
        ),
    ]
